### ISSUE TITLE
"Could not find language locale file, aborting..." Error

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/astronomer-cli#1]
Mac OS 10.12.6
Python 3.6.2

```
Benjamins-MacBook-Pro:~ tardis5$ astro
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/astro", line 11, in <module>
    load_entry_point('astronomer-cli==0.1', 'console_scripts', 'astro')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/src/main.py", line 14, in <module>
    from .utils.lang import Lang
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/src/utils/lang.py", line 44, in <module>
    Lang.load_translations()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/src/utils/lang.py", line 22, in load_translations
    raise common.AstroGenericException('Could not find language locale file, aborting...')
src.utils.common.AstroGenericException: Could not find language locale file, aborting...

```

**Comment by tedmiston** [comment]
@benjamingregory Can you run `which python` and `which python3` and paste the output?

3.6.2 is pretty new so it's possible you're the first to test in it.

**Comment by benjamingregory** [comment]
`which python` 
/usr/bin/python

`which python3`
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3

**Comment by cwurtz** [comment]
Fixed, in addition to the problem that pip was installing the CLI under the name "src" which is no fixed, the problem was by default pip won't copy non python packages.  (To be more specific you either specify each package that is included or use "find_packages()", either way the locale files are json and not a python package, so it didn't get copied
